LE: EQU 1
SECTION TEXT
INPUT OLD_DATA
LOAD OLD_DATA
L1: DIV DOIS
STORE  NEW_DATA
MULT DOIS
STORE TMP_DATA
LOAD OLD_DATA
SUB TMP_DATA
STORE TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA+123, OLD_DATA
LOAD OLD_DATA
JMPP L1
STOP
SECTION DATA
DOIS: CONST 2
OLD_DATA: SPACE
MYMACRO 1, 2, 3
NEW_DATA: SPACE
TMP_DATA: SPACE
LABEL: COPY +ASDF+12, ASDF+FDSA, fdas+423 ; LAWEEJFASEKLJFL
MYMACRO: MACRO A1, A2, A3
COPY A1, A2, LE
DIV A1
ENDMACRO
ASDF: ADSF 2,3
MYMACRO2: MACRO T2324, LSEFJ3, 32I0I
JMPP T2324
STOP
SECTION DATA
DOIS: CONST 2
OLD_DATA: SPACE
ENDMACRO
MYMACRO 1, 3, 1
